# Generated by Django 6.0.6 on 2026-06-18 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_ads", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
